#pragma once

// next id = 39

#define  BUTTON_CLEAR_DRIVE 11
#define  BUTTON_SEARCH_FILES 19
#define  BUTTON_DELETE_FILES 20
#define  BUTTON_DELETE_ALL_FILES 21
#define  BUTTON_ADD_EXTENSION 24
#define  BUTTON_DELETE_EXTENSION 25
#define  BUTTON_SET_PATH 33
#define  BUTTON_SET_COPY_PATH 35
#define  BUTTON_COPY_TO_SELECTED_FOLDER 36
#define  BUTTON_COPY_ALL 38


#define  CHECKBOX_USE_SIZE_BORDER 26
#define  CHECKBOX_USE_EXTENSION 27
#define  CHECKBOX_USE_NAME_TEMPLATE 28
#define  CHECKBOX_CASE_SENSITIVE_TEMPL 30
#define  CHECKBOX_USE_MAX_COUNT 31
#define  CHECKBOX_DELETE_AFTER_COPY 37

#define  LISTBOX_FLASHDRIVE 12

#define  EDIT_MAX_SIZE 14
#define  EDIT_MIN_SIZE 15
#define  EDIT_MAX_SEARCH_NESTING 18
#define  EDIT_CURRENT_PATH 22
#define  EDIT_NAME_TEMPLATE 29
#define  EDIT_MAX_COUNT 32
#define  EDIT_COPY_PATH 34


#define  COMBOBOX_SIZE 16
#define  COMBOBOX_EXTENSION 23

#define  LISTVIEW_FILES 17

