#pragma once

// next id = 26

#define  BUTTON_CLEAR_DRIVE 11
#define  BUTTON_SEARCH_FILES 19
#define  BUTTON_DELETE_FILES 20
#define  BUTTON_DELETE_ALL_FILES 21
#define  BUTTON_ADD_EXTENSION 24
#define  BUTTON_DELETE_EXTENSION 25


#define  LISTBOX_FLASHDRIVE 12

#define  EDIT_MAX_SIZE 14
#define  EDIT_MIN_SIZE 15
#define  EDIT_MAX_SEARCH_NESTING 18
#define  EDIT_CURRENT_PATH 22


#define  COMBOBOX_SIZE 16
#define  COMBOBOX_EXTENSION 23

#define  LISTVIEW_FILES 17

